### ISSUE TITLE
Opening Epub from Assets?

### ISSUE THREAD

**Issue by voipworld** [databoxtech/flutter_epub_viewer#3]
Hello,
i'm trying to open my book from assets using this code:
import 'package:flutter/material.dart';
import 'dart:async';
import 'package:r2_viewer/r2_viewer.dart';

void main() {
R2Viewer.openEpub("assets/1.epub", 1);
}
but its not opening, any idea?

**Comment by voipworld** [comment]
Debug log: 
09-22 19:59:49.795  8974  9569 E SystemUpdate-ConnectionRSA: get key exception : com.android.org.bouncycastle.util.encoders.DecoderException: unable to decode base64 string: invalid characters encountered in base64 data                     
09-22 19:59:50.470  9431  9431 E AndroidRuntime: kotlin.KotlinNullPointerException                                      
09-22 19:59:50.470  9431  9431 E AndroidRuntime:        at io.databoxtech.r2_viewer.epub.MainActivity.presentOpeningException(MainActivity.kt:154)                                                                                              
09-22 19:59:50.470  9431  9431 E AndroidRuntime:        at io.databoxtech.r2_viewer.epub.MainActivity.access$presentOpeningException(MainActivity.kt:40)                                                                                        
09-22 19:59:50.664  1732  1847 W WindowManager: android.os.DeadObjectException                                          
09-22 20:01:08.536  9901  9901 E AndroidRuntime: kotlin.KotlinNullPointerException                                      
09-22 20:01:08.536  9901  9901 E AndroidRuntime:        at io.databoxtech.r2_viewer.epub.MainActivity.presentOpeningException(MainActivity.kt:154)                                                                                              
09-22 20:01:08.536  9901  9901 E AndroidRuntime:        at io.databoxtech.r2_viewer.epub.MainActivity.access$presentOpeningException(MainActivity.kt:40)
